<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>profilname_meitesting</name>
   <tag></tag>
   <elementGuidId>e82da0c7-77e5-46fe-973f-51df7a903f0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='hello-text']//span[contains(text(),'meitesting')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#hello-text > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6cf3c560-b30e-4697-b724-dfb8ccd32930</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>meitesting</value>
      <webElementGuid>9815b494-46a6-44f4-acb0-288485a8ea17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hello-text&quot;)/span[1]</value>
      <webElementGuid>367ae834-d504-4009-89da-5ad5d2988847</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='hello-text']/span</value>
      <webElementGuid>d4e3be1a-7cfa-418c-9f56-257021fba9a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rekomendasi untukmu'])[1]/following::span[1]</value>
      <webElementGuid>3ddda06e-7eaf-4555-b419-52af97238bca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pesanan Saya'])[1]/preceding::span[1]</value>
      <webElementGuid>c650cc14-ab0e-4b8d-8d98-5b0bd0d7eedf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Akun Saya'])[1]/preceding::span[1]</value>
      <webElementGuid>538ce49e-ac4a-4907-acf9-541e824c0d04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='meitesting']/parent::*</value>
      <webElementGuid>dca5efe1-7883-4d86-9a87-78afbcb08b70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/span</value>
      <webElementGuid>fdd4341d-1e49-4d8e-a742-45b43a820c6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'meitesting' or . = 'meitesting')]</value>
      <webElementGuid>ecc81dbe-ed4f-4034-bf10-2601d70a9f7d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
